### ISSUE TITLE
Ggml model available?

### ISSUE THREAD

**Issue by linouxis9** [bofenghuang/vigogne#1]
Thanks for sharing! Looks great :-)
Would you happen to share the ggml model of fine tuned LLaMA using vigogne datasets? 😄

**Comment by bofenghuang** [comment]
Hi @linouxis9 !

Thanks for your interest. Unfortunately, the complete model weights cannot be released in this project since Facebook has not made the official LLaMA model weights open source.

You could refer to this [section](https://github.com/bofenghuang/vigogne#try-it-out-on-your-own-pc) how to combine the model then quantize.

**Comment by pereconteur** [comment]
Hi, I wish I could have it on my computer! Is the model.bin file directly downloadable?

Does it work with Alpaca?

**Comment by bofenghuang** [comment]
Hi @pereconteur !

This project is a sort of fork of Alpaca in French, designed to follow French instructions. You can combine the shared Vigogne-LoRA weights with the base LLaMA model, but not with the Alpaca model.
